#!/bin/sh

#
# Warp 10 - Standalone
#
# chkconfig: 2345 90 30
# description: Manage Standalone instance of Warp 10
#

WARP10_USER=warp10
#WARP10_HOME=/opt/warp10-@VERSION@

#
# Make sure the caller is root
#

if [ "`whoami`" != "root" ]
then
  echo "You must be root to run '$0'"
  exit 1
fi

if [ "$1" = "bootstrap" ]; then
  ${WARP10_HOME}/bin/warp10-standalone.sh bootstrap
else
  args="$@"
  su ${WARP10_USER} -c "${WARP10_HOME}/bin/warp10-standalone.sh $args"
fi

exit $?