os: linux
dist: bionic

addons:
  apt:
    packages:
      - thrift-compiler

language: java
jdk:
  - openjdk8

script:
  - ./gradlew -Djava.security.egd=file:/dev/urandom warp10:pack

notifications:
  email: false
